# Generated by Django 2.1.15 on 2022-12-08 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221208_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isAdmin',
        ),
    ]
