# Generated by Django 2.1.15 on 2022-12-08 13:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=30, null=True)),
                ('reference', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=10, null=True)),
                ('priority', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True)),
                ('durationMonths', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('sales', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Proposed', 'Proposed'), ('Resource needed', 'Resource needed'), ('Interview', 'Interview'), ('Won', 'Won'), ('No goal', 'No goal'), ('Lost', 'Lost')], max_length=15, null=True)),
                ('internalComments', models.TextField(blank=True, null=True)),
                ('clientComment', models.TextField(blank=True, null=True)),
                ('started', models.DateField(blank=True, null=True)),
                ('dateProposed', models.DateField(blank=True, null=True)),
                ('ended', models.DateField(blank=True, null=True)),
                ('uptaded', models.DateField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Channel')),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Profile')),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Faction')),
            ],
            options={
                'ordering': ['ended'],
            },
        ),
    ]
