# Generated by Django 2.1.15 on 2022-12-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20221208_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='sales',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
