# Generated by Django 2.1.15 on 2022-12-08 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20221209_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultant_request', to='users.Faction'),
        ),
        migrations.AlterField(
            model_name='request',
            name='sales',
            field=models.ForeignKey(blank=True, limit_choices_to={'isSaler': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saler_request', to='users.Profile'),
        ),
    ]
